version: '3.9'

name: soundglide_backend_dev

services:
  postgres:
    restart: always
    env_file: ./dev.env
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - dev-database-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=soundglide
      - POSTGRES_PASSWORD=9&UJ9@h&y09TGl1U
      - POSTGRES_DB=soundglide
      - POSTGRES_HOST=host.docker.internal
    networks:
      - nestjs-network
  nest:
    depends_on:
      - postgres
    restart: always
    env_file: ./dev.env
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    networks:
      - nestjs-network

volumes:
  dev-database-data:

networks:
  nestjs-network:
