version: '3'

name: soundglide_backend_dev

services:
  database:
    restart: always
    env_file: ./dev.env
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: soundglide

volumes:
  database-data:
