version: '3'

name: soundglide-backend-prod

services:
  database:
    restart: always
    env_file: ./prod.env
    image: postgres:14
    ports:
      - 4675:5432
    volumes:
      - database-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: soundglide
      POSTGRES_PASSWORD: m2fwn@9Coq$6Cw28
      POSTGRES_DB: soundglide
  backend:
    depends_on: 
      - database
    restart: always
    env_file: ./prod.env
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 80:3000

volumes:
  database-data:
